version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    container_name: bikepos-couchdb
    environment:
      - COUCHDB_USER=${VITE_COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${VITE_COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_config:/opt/couchdb/etc/local.d
    networks:
      - bikepos-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s