export interface ProductDocType {
    id: string
    name: {
        en: string
        si: string
    }
    description: {
        en: string
        si: string
    }
    category: string
    barcode: string
    price: number
    cost: number
    stock: {
        store1: number
        store2: number
    }
    minStock: number
    supplier: string
    createdAt: string
    updatedAt: string
}

export const products: ProductDocType[] = [
    {
        id: "P003",
        name: { en: "Bill", si: "සිංහල_Bill" },
        description: { en: "High quality bill", si: "ඉතා උසස් සිංහල_Bill" },
        category: "Electronics",
        barcode: "4981833454",
        price: 32.24,
        cost: 20.77,
        stock: { store1: 67, store2: 33 },
        minStock: 6,
        supplier: "Howard-Pena",
        createdAt: "2025-04-14",
        updatedAt: "2025-06-13",
    },
    {
        id: "P004",
        name: { en: "Animal", si: "සිංහල_Animal" },
        description: { en: "High quality animal", si: "ඉතා උසස් සිංහල_Animal" },
        category: "Fruits",
        barcode: "3322980935",
        price: 30.05,
        cost: 19.74,
        stock: { store1: 5, store2: 43 },
        minStock: 10,
        supplier: "Robinson-Hopkins",
        createdAt: "2024-06-21",
        updatedAt: "2025-06-13",
    },
    // Previous 13 items remain unchanged...
    // New items start from P016 to P040:
    {
        id: "P016",
        name: { en: "Laptop", si: "සිංහල_Laptop" },
        description: { en: "High performance laptop", si: "ඉතා උසස් සිංහල_Laptop" },
        category: "Electronics",
        barcode: "1234567890",
        price: 899.99,
        cost: 650.50,
        stock: { store1: 15, store2: 8 },
        minStock: 5,
        supplier: "Tech Solutions Inc",
        createdAt: "2024-05-10",
        updatedAt: "2025-06-01",
    },
    {
        id: "P017",
        name: { en: "Smartphone", si: "සිංහල_Smartphone" },
        description: { en: "Latest model smartphone", si: "නවතම ආකෘතියේ සිංහල_Smartphone" },
        category: "Electronics",
        barcode: "2345678901",
        price: 699.99,
        cost: 500.25,
        stock: { store1: 22, store2: 18 },
        minStock: 10,
        supplier: "Mobile World",
        createdAt: "2024-06-15",
        updatedAt: "2025-05-20",
    },
    {
        id: "P018",
        name: { en: "Headphones", si: "සිංහල_Headphones" },
        description: { en: "Noise cancelling headphones", si: "ශබ්ද අවහිර කරන සිංහල_Headphones" },
        category: "Electronics",
        barcode: "3456789012",
        price: 199.99,
        cost: 120.75,
        stock: { store1: 7, store2: 25 },
        minStock: 8,
        supplier: "Audio Tech",
        createdAt: "2024-07-20",
        updatedAt: "2025-04-15",
    },
    {
        id: "P019",
        name: { en: "Apple", si: "සිංහල_Apple" },
        description: { en: "Fresh red apples", si: "තාත්තා රතු සිංහල_Apple" },
        category: "Fruits",
        barcode: "4567890123",
        price: 1.99,
        cost: 0.99,
        stock: { store1: 20, store2: 95 },
        minStock: 50,
        supplier: "Fresh Farms",
        createdAt: "2024-08-05",
        updatedAt: "2025-06-10",
    },
    {
        id: "P020",
        name: { en: "Banana", si: "සිංහල_Banana" },
        description: { en: "Organic bananas", si: "කාබනික සිංහල_Banana" },
        category: "Fruits",
        barcode: "5678901234",
        price: 0.79,
        cost: 0.35,
        stock: { store1: 200, store2: 150 },
        minStock: 75,
        supplier: "Tropical Fruits Co",
        createdAt: "2024-09-12",
        updatedAt: "2025-06-12",
    },
    {
        id: "P021",
        name: { en: "Milk", si: "සිංහල_Milk" },
        description: { en: "Fresh whole milk", si: "නැතුව තරම් සිංහල_Milk" },
        category: "Dairy",
        barcode: "6789012345",
        price: 3.49,
        cost: 2.10,
        stock: { store1: 45, store2: 60 },
        minStock: 30,
        supplier: "Dairy Farms",
        createdAt: "2024-10-18",
        updatedAt: "2025-06-13",
    },
    {
        id: "P022",
        name: { en: "Eggs", si: "සිංහල_Eggs" },
        description: { en: "Free range eggs", si: "නිදහස් පරාස සිංහල_Eggs" },
        category: "Dairy",
        barcode: "7890123456",
        price: 4.99,
        cost: 3.25,
        stock: { store1: 80, store2: 70 },
        minStock: 40,
        supplier: "Happy Hens",
        createdAt: "2024-11-22",
        updatedAt: "2025-06-11",
    },
    {
        id: "P023",
        name: { en: "Rice", si: "සිංහල_Rice" },
        description: { en: "Basmati rice 5kg", si: "බස්මති සිංහල_Rice 5kg" },
        category: "Groceries",
        barcode: "8901234567",
        price: 12.99,
        cost: 8.50,
        stock: { store1: 35, store2: 40 },
        minStock: 20,
        supplier: "Grain Masters",
        createdAt: "2024-12-10",
        updatedAt: "2025-05-30",
    },
    {
        id: "P024",
        name: { en: "Pasta", si: "සිංහල_Pasta" },
        description: { en: "Whole wheat pasta", si: "සම්පූර්ණ තිරිඟු සිංහල_Pasta" },
        category: "Groceries",
        barcode: "9012345678",
        price: 2.49,
        cost: 1.50,
        stock: { store1: 20, store2: 55 },
        minStock: 25,
        supplier: "Pasta Italia",
        createdAt: "2025-01-15",
        updatedAt: "2025-06-05",
    },
    {
        id: "P025",
        name: { en: "Shampoo", si: "සිංහල_Shampoo" },
        description: { en: "Moisturizing shampoo", si: "ආර්ද්රතාවය පවත්වා ගන්නා සිංහල_Shampoo" },
        category: "Personal Care",
        barcode: "0123456789",
        price: 7.99,
        cost: 4.75,
        stock: { store1: 25, store2: 30 },
        minStock: 15,
        supplier: "Beauty Essentials",
        createdAt: "2025-02-20",
        updatedAt: "2025-06-08",
    },
    {
        id: "P026",
        name: { en: "Toothpaste", si: "සිංහල_Toothpaste" },
        description: { en: "Fluoride toothpaste", si: "ෆ්ලෝරයිඩ් සිංහල_Toothpaste" },
        category: "Personal Care",
        barcode: "9876543210",
        price: 3.99,
        cost: 2.25,
        stock: { store1: 50, store2: 45 },
        minStock: 20,
        supplier: "Dental Care Inc",
        createdAt: "2025-03-05",
        updatedAt: "2025-06-09",
    },
    {
        id: "P027",
        name: { en: "Towel", si: "සිංහල_Towel" },
        description: { en: "Soft cotton towel", si: "මෘදු කපු සිංහල_Towel" },
        category: "Home",
        barcode: "8765432109",
        price: 12.99,
        cost: 8.00,
        stock: { store1: 20, store2: 25 },
        minStock: 10,
        supplier: "Home Comfort",
        createdAt: "2025-04-10",
        updatedAt: "2025-05-25",
    },
    {
        id: "P028",
        name: { en: "Pillow", si: "සිංහල_Pillow" },
        description: { en: "Memory foam pillow", si: "මතක තරු සිංහල_Pillow" },
        category: "Home",
        barcode: "7654321098",
        price: 29.99,
        cost: 18.50,
        stock: { store1: 15, store2: 12 },
        minStock: 8,
        supplier: "Sleep Well",
        createdAt: "2025-05-15",
        updatedAt: "2025-06-07",
    },
    {
        id: "P029",
        name: { en: "Battery", si: "සිංහල_Battery" },
        description: { en: "AA alkaline batteries", si: "AA ඇල්කලයින් සිංහල_Battery" },
        category: "Electronics",
        barcode: "6543210987",
        price: 8.99,
        cost: 5.50,
        stock: { store1: 40, store2: 35 },
        minStock: 20,
        supplier: "Power Solutions",
        createdAt: "2025-06-01",
        updatedAt: "2025-06-12",
    },
    {
        id: "P030",
        name: { en: "Flashlight", si: "සිංහල_Flashlight" },
        description: { en: "LED flashlight", si: "LED සිංහල_Flashlight" },
        category: "Electronics",
        barcode: "5432109876",
        price: 15.99,
        cost: 9.75,
        stock: { store1: 18, store2: 22 },
        minStock: 10,
        supplier: "Bright Lights",
        createdAt: "2025-01-30",
        updatedAt: "2025-05-20",
    },
    {
        id: "P031",
        name: { en: "Backpack", si: "සිංහල_Backpack" },
        description: { en: "Waterproof backpack", si: "ජලය නොපැහැරෙන සිංහල_Backpack" },
        category: "Stationery",
        barcode: "4321098765",
        price: 39.99,
        cost: 25.00,
        stock: { store1: 12, store2: 15 },
        minStock: 5,
        supplier: "Travel Gear",
        createdAt: "2025-02-28",
        updatedAt: "2025-06-02",
    },
    {
        id: "P032",
        name: { en: "Umbrella", si: "සිංහල_Umbrella" },
        description: { en: "Windproof umbrella", si: "සුළං නොපැහැරෙන සිංහල_Umbrella" },
        category: "Accessories",
        barcode: "3210987654",
        price: 19.99,
        cost: 12.50,
        stock: { store1: 25, store2: 20 },
        minStock: 10,
        supplier: "Weather Protection",
        createdAt: "2025-03-15",
        updatedAt: "2025-05-15",
    },
    {
        id: "P033",
        name: { en: "Watch", si: "සිංහල_Watch" },
        description: { en: "Digital sports watch", si: "ඩිජිටල් ක්රීඩා සිංහල_Watch" },
        category: "Accessories",
        barcode: "2109876543",
        price: 49.99,
        cost: 32.00,
        stock: { store1: 8, store2: 10 },
        minStock: 5,
        supplier: "Time Masters",
        createdAt: "2025-04-05",
        updatedAt: "2025-06-10",
    },
    {
        id: "P034",
        name: { en: "Sunglasses", si: "සිංහල_Sunglasses" },
        description: { en: "UV protection sunglasses", si: "UV ආරක්ෂිත සිංහල_Sunglasses" },
        category: "Accessories",
        barcode: "1098765432",
        price: 29.99,
        cost: 18.00,
        stock: { store1: 15, store2: 12 },
        minStock: 8,
        supplier: "Sun Protection",
        createdAt: "2025-05-10",
        updatedAt: "2025-06-11",
    },
    {
        id: "P035",
        name: { en: "Yogurt", si: "සිංහල_Yogurt" },
        description: { en: "Greek yogurt", si: "ග්රීක සිංහල_Yogurt" },
        category: "Dairy",
        barcode: "0987654321",
        price: 2.99,
        cost: 1.75,
        stock: { store1: 35, store2: 40 },
        minStock: 20,
        supplier: "Dairy Delights",
        createdAt: "2025-06-05",
        updatedAt: "2025-06-13",
    },
    {
        id: "P036",
        name: { en: "Cheese", si: "සිංහල_Cheese" },
        description: { en: "Cheddar cheese block", si: "චෙඩර් ප්ලොක් සිංහල_Cheese" },
        category: "Dairy",
        barcode: "9876543210",
        price: 5.99,
        cost: 3.50,
        stock: { store1: 25, store2: 30 },
        minStock: 15,
        supplier: "Cheese Masters",
        createdAt: "2025-01-20",
        updatedAt: "2025-05-30",
    },
    {
        id: "P037",
        name: { en: "Butter", si: "සිංහල_Butter" },
        description: { en: "Salted butter", si: "ලුණු සිංහල_Butter" },
        category: "Dairy",
        barcode: "8765432109",
        price: 4.49,
        cost: 2.75,
        stock: { store1: 30, store2: 25 },
        minStock: 15,
        supplier: "Dairy Gold",
        createdAt: "2025-02-15",
        updatedAt: "2025-06-08",
    },
    {
        id: "P038",
        name: { en: "Coffee", si: "සිංහල_Coffee" },
        description: { en: "Arabica coffee beans", si: "අරාබි සිංහල_Coffee" },
        category: "Beverages",
        barcode: "7654321098",
        price: 12.99,
        cost: 8.00,
        stock: { store1: 18, store2: 15 },
        minStock: 10,
        supplier: "Coffee Masters",
        createdAt: "2025-03-10",
        updatedAt: "2025-05-25",
    },
    {
        id: "P039",
        name: { en: "Tea", si: "සිංහල_Tea" },
        description: { en: "Green tea bags", si: "හරිත තේ බෑග් සිංහල_Tea" },
        category: "Beverages",
        barcode: "6543210987",
        price: 5.99,
        cost: 3.50,
        stock: { store1: 40, store2: 35 },
        minStock: 20,
        supplier: "Tea Time",
        createdAt: "2025-04-20",
        updatedAt: "2025-06-05",
    },
    {
        id: "P040",
        name: { en: "Cereal", si: "සිංහල_Cereal" },
        description: { en: "Whole grain cereal", si: "සම්පූර්ණ ධාන්ය සිංහල_Cereal" },
        category: "Groceries",
        barcode: "5432109876",
        price: 4.99,
        cost: 3.00,
        stock: { store1: 25, store2: 30 },
        minStock: 15,
        supplier: "Breakfast Foods",
        createdAt: "2025-05-25",
        updatedAt: "2025-06-12",
    }
];




